name: Release version

on:
  status
  
jobs:
  release:
    #Create a pre-release with the content of version.txt file
    name: Create Pre-Release
    if: github.event.state == 'success'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Generate env variable VERSION based on version.txt file
      - name: Generate image name
        run: |
          cat ./version.txt | sed 's/^/VERSION=' >> $GITHUB_ENV
          
      # Generate pre-release version
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          prerelease: true
